[package]
name = "framework-devserver"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1", features = ["full"] }
hyper = { version = "1" }
hyper-util = { version = "0.1", features = ["tokio"] }
http-body-util = "0.1"
