name: Mark stale issues and pull requests

on:
  schedule:
    - cron: '40 4 * * *' # runs daily at 4:40 UTC

jobs:
  stale:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write

    steps:
      - uses: actions/stale@v5
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          stale-issue-message: |
            This issue has not had any activity for a while. 
            If it is still relevant, please update it or comment to keep it open. 
            Otherwise, it will be closed automatically. 
            For guidance on contributing, see CONTRIBUTING.md.
          stale-pr-message: |
            This pull request has not had any activity for a while. 
            If you are still working on it, please update or comment to keep it open. 
            Otherwise, it will be closed automatically. 
            See CONTRIBUTING.md for guidance on making updates.
          stale-issue-label: 'no-issue-activity'
          stale-pr-label: 'no-pr-activity'
          days-before-stale: 30
          days-before-close: 7
          exempt-issue-labels: 'pinned,good first issue'
          exempt-pr-labels: 'pinned'
